#1 only import the cssParse function we need
testing-library/jasmine-dom pull request #8
Opened 2020-12-09 09:38 UTC by IanGrainger

**What**:

We can't import the CSS library in the browser (which is how Karma runs the tests) - because of an error `Module not found: Error: Can't resolve 'fs'`. But as suggested by a developer on that project, we can just import the function we need from the library.

**Why**:

Because attempting to run tests with Karma results in an error: `Module not found: Error: Can't resolve 'fs'`.

**How**:

Import the cssParse function we need rather than the whole css library.

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [ ] Updated Type Definitions
- [x] Ready to be merged

2020-12-09 09:42 UTC, IanGrainger commented
Oh dear. Looks like a caching problem in your build script? :(

2020-12-09 20:13 UTC, ogonkov approved these changes
Looking forward to see it merged

2020-12-09 20:17 UTC, ogonkov requested changes

2020-12-09 20:17 UTC, ogonkov commented on src/toHaveStyle.js
> +import cssParse from 'css/lib/parse';
I guess that should be on the first line in this file, since it is module dependency, then own dependencies goes

2020-12-09 22:02 UTC, brrianalexis commented
> Oh dear. Looks like a caching problem in your build script? :(

![The Office - MIchael Scott -I Don't Know What The Fuck That Was](https://i.makeagif.com/media/9-17-2018/8lYUAc.gif)
Maybe running actions on windows wasn't such a great idea 😅

I'll try this out on the weekend @IanGrainger! Let's hope for the best.

Thank you for your support and your efforts.

2020-12-10 08:22 UTC, IanGrainger commented
I've pushed changing the import order. Sorry about that! 😅 

Hey, how'd the new job go? Did you get it?? 😄

2020-12-10 09:26 UTC, ogonkov approved these changes

2020-12-13 19:34 UTC, brrianalexis approved these changes

2020-12-13 19:34 UTC, brrianalexis commented
I did get a new job, thanks for asking! 😄

Thank you for putting so much work into this.

2020-12-13 19:35 UTC, merged

2020-12-13 19:38 UTC, brrianalexis commented
@all-contributors add @IanGrainger for code